### PR TITLE
Update errors for JSON parsing-- register form

### PR DESCRIPTION
**Pull request by lyremlou**
register form front end with some backend json parsing updates

### CODE REVIEW

**Review by jlacy93 — CHANGES_REQUESTED** [review]
-Angular form is sending password as username
`        <div class="mb-3">
            <label for="confirmPassword" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="confirmPassword" aria-describedby="confirmPasswordField" formControlName="firstName"> /*should be password*/
          </div>`
          
-Spring component valiadation to use isEmpty() instead of null. Replace strucutre of when the user object is created

**Comment by lyremlou** [comment]
I pushed my fixes, file is changed!

**Review by Meliora347 — APPROVED** [review]

**Review by jlacy93 — CHANGES_REQUESTED** [review]
Angular piece is still updating firstName with the value in the confirm password field.
image

**Comment by lyremlou** [comment]
My register component didn't get added to the list of files to be pushed for some reason. I double checked, it is there now. I also merged with main before I pushed.

**Review by jlacy93 — CHANGES_REQUESTED** [review]
image
Users are not being registered since logic is being bypassed. We want to check that these values are NOT blank before creating the user instead of checking if they are blank.

**Comment by lyremlou** [comment]
Added bangs on line 57 in authentication controller

**Review by jlacy93 — APPROVED** [review]
Everything is working! Great job!

**Pull request merged**
