### PR TITLE
Front end form data posts successfully to backend MySQL database

### PR DESCRIPTION
**Pull request by Meliora347**
In your MySQL database, you will also be seeing the test I wrote show up ("I'm a cat that needs help!").

### CODE REVIEW

**Review by jlacy93 — CHANGES_REQUESTED** [review]
It looks like the field "reason_for_contact" on the backend isn't getting populated by the field "selectedSubject" on the front end.

image

The only thing I could think of is the mismatch in naming potentially?

Thanks!!

**Review by lyremlou — COMMENTED** [review]
I think I'm seeing the old version of your code, like you said. 

Nothing is populating in my db. I made sure intellij was running, made sure the connection was good, etc. I'm not sure why 

Screenshot 2023-10-29 at 11 51 09 AM

**Review by lyremlou — APPROVED** [review]
Great job!

**Review by jlacy93 — APPROVED** [review]
Approved!

**Pull request merged**
